### PR TITLE
translate the website to Arabic

### PR DESCRIPTION
**Pull request by Gattalraouf**
I managed both translating the website into the Arabic language. yet for better visualization I was wondering if you know of an easy way to switch the direction from "ltr" to "rtl" since Arabic is "rtl".
Otherwise I'll try to do it manually and made another PR as soon as I can.

### CODE REVIEW

**Comment by Miloshinjo** [comment]
Hey, thanks for the translation.

I am not familiar with ltr and rtl, this means that Arabic is written from
right-to-left and just the text needs to be reversed?

How do the translations work now? Unless it's not right-to-left, they do
not work?

best,
Milos

**Comment by Gattalraouf** [comment]
It's working basically yet the visualization isn't the best.
I was talking about css, apparently you didn't take in consideration, I will try to manage it in another PR asap.meanwhile you can merge this PR as it is, everything is good. I am a perfectionist that's why xd
 
image

**Comment by Miloshinjo** [comment]
Yes, so you mean the screen to be oriented like in the mirror, from the
right?

I guess you can try it, just some context has to be attached smth like "if
(arabic) move stuff to right".

If you don't succeed, give me a rough drawing of how it should look like
and I'll do my best :)

Best,
Milos

**Comment by Gattalraouf** [comment]
Exactly, I will work on it. 
Thank you.

**Comment by Gattalraouf** [comment]
If you found anything wrong just tell me and i'll fix it.

**Comment by Miloshinjo** [comment]
Alright, I'll review it tonight or tomorrow morning :) Cheers!

**Comment by Miloshinjo** [comment]
Hi, I did the review and I have a few comments.

I like how it looks. 

1) About the numbers, they are still aligned to the left, is that acceptable or by the rules in Arabic? If you had trouble moving them right, I can do it.

2) I noticed you are using double equals to check `==`, my linter is giving me noise about it, basicly, always use triple equals and you will have no issues `===`. :) (check type coercion in JS if not already).

3) The "Arabic" on the language select upper right, can you make it be in Arabic, since every other option I have made in it's native lang :)

That's it :) fix that and I merge.

**Pull request merged**
